[package]
name = "gitcc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
dialoguer = "0.11.0"
git2 = "0.18.1"
gpgme = "0.11.0"
ring = "0.16.20"
